{
 "title": "Humedat@ - Atlas",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Léeme",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Humedat@ -- Isla San Francisco\n\nHas entrado al visualizador web de **Humedat@, plataforma en tiempo real para el monitoreo de calidad de aguas** de humedales de Chile.\n\nHumedat@ es una innovación tecnológica nacida en Valdivia, e impulsada por el [Centro de Humedales Río Cruces (CEHUM)](https://cehum.org/). \n\nConsiste en boyas de acero inox hechas con barriles cerveceros reutilizados, con múltiples sensores ambientales y electrónica de fuente abierta para la transmisión inalámbrica constante de datos desde diversos ecosistemas acuáticos hasta usuarios como tú. El aparato tiene tres conjuntos de sensores: 1) sensores acuáticos tales como T, pH, conductividad\neléctrica, oxígeno disuelto, y potencial de oxido-reducción; 2) sensores atmosféricos tales como temperatura y presión atmosférica; y 3) sensores internos que monitorean y resguardan el ambiente electrónico dentro del barril incluyendo estanqueidad, humedad del aire interno, temperatura, y estado de carga de baterías.\n\nEl desarrollo liderado por el [Dr. Cristián Correa](https://scholar.google.ca/citations?user=H3toP-0AAAAJ&hl=en) (cristiancorrea@gmail.com) ha contado con la colaboración del Laboratorio de Fabricación Digital [LeufüLab](https://leufulab.cl/) de la Facultad de Ciencias de la Ingeniería UACh. \nActualmente (2023) se encuentra financiado por el [Proyecto de Conservación Habitable Isla San Francisco](https://islasanfrancisco.cl/), con aportes de [Cerveza Kunstmann](https://cerveza-kunstmann.cl/).\n\nNo dudes en contactarnos para más información, cotizar, establecer sinergias estratégicas, colaborar o aportar monetaria o intelectualmente para que Humedat@ continúe creciendo y aportando información clave para la conservación de humedales. \n\n**Versión beta**: vandrán muchas actualizaciones cosméticas y analíticas, incluyendo un número de ajustes/correcciones de parámetros de calidad de agua.   \n\n[Centro de Humedales Río Cruces](https://cehum.org/)  \n\ncontacto@cehum.org"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM logs\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Dashboard - ALL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ubicación",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  latitude,\n  longitude\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = 1\nORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Tiempo entre mediciones recibidas remotamente",
   "type": "timeseries",
   "description": "Esto es para estudiar frecuencia de flujo de datos. Internamente Humedat@ registra mediaciones regularmente (actualmente programado cada 15 min).",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "-- SQL Script for Grafana Dashboard to Monitor Time Elapsed Between Data Packages Reception\r\n\r\nSELECT\r\n  DATE_SUB(a.timestamp, INTERVAL 0 HOUR) AS \"time\",\r\n  TIMESTAMPDIFF(MINUTE, b.timestamp, a.timestamp) AS \"time_elapsed_in_minutes\"\r\nFROM\r\n  (SELECT *, @row_number_a:=@row_number_a + 1 AS rn FROM logs, (SELECT @row_number_a:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '1' ORDER BY timestamp) a\r\nJOIN\r\n  (SELECT *, @row_number_b:=@row_number_b + 1 AS rn FROM logs, (SELECT @row_number_b:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '1' ORDER BY timestamp) b\r\nON\r\n  a.rn = b.rn + 1\r\nORDER BY\r\n  a.timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Presión Atmosférica",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expression": "$A*10", "type": "math" }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  atmospheric_temperature AS `Temperatura Atmosférica`,\n  internal_temperature AS `Temperatura Interna`,\n  water_temperature AS `Temperatura del Agua`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Oxígeno Disuelto",
   "type": "timeseries",
   "description": "0-3: Riesgo de anoxia\n3-5: Hipoxia\n5-10: Normoxia",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mg/L" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  dissolved_oxygen AS `Raw DO`,\n  do_15 AS 'DO at 15°C',\n  do_temp AS 'DO at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Saturación de Oxígeno (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  sat AS `RAW SAT`,\n  sat_temp AS 'SAT at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Potencial de Óxido Reducción",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  oxide_reduction_potential AS `Potencial de Reduccción`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Conductividad Eléctrica",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  electrical_conductivity AS `RAW EC`,\n  ec_temp AS 'EC at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Sólidos Disueltos Totales",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  total_dissolved_solids\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  ph AS 'pH',\n  ph_temp 'pH at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Voltaje Batería",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  battery_level\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Humedad Interna",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  internal_humidity AS `Humedad Interna`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Presión Interna Barril",
   "type": "timeseries",
   "description": "Este es una indicación de la estanqueidad del barril y seguridad de la electrónica. Mientras tenga presión positiva, no hay riesgo de infiltración de agua.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expression": "$B*10", "type": "math" }
   ]
  },
  {
   "title": "Funcionamiento interno",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live data",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_humidity AS 'Humedad interna'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
      },
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_pressure AS 'Presión interna'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp  "
      },
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_temperature AS 'Temperatura interna'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp  "
      }
     ]
    },
    {
     "title": "Temperatura interna",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 12, "y": 39 },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_temperature AS `Temperatura Interna`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Batería",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 4, "x": 20, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  battery_level\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Presión interna",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      { "expression": "$B*10", "type": "math" }
     ]
    },
    {
     "title": "Humedad Interna",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_humidity AS `Humedad Interna`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Live data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperaturas",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  atmospheric_temperature AS `Atmosférica`,\n  internal_temperature AS `Interna`,\n  water_temperature AS `Agua`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Oxígeno Disuelto",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "mg/L" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  dissolved_oxygen AS `Raw`,\n  do_15 AS 'DO at 15°C',\n  do_temp AS 'DO at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Ubicación",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  latitude,\n  longitude\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = 1\nORDER BY id DESC LIMIT 1"
      }
     ]
    },
    {
     "title": "pH",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "pH" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  ph AS 'Raw',\n  ph_temp 'pH at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = 1\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Registros",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Datos históricos Humedat@ Atlas",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "rawSql": "SELECT id,\n       atmospheric_pressure AS 'Presión atmosférica',\n       atmospheric_temperature AS 'Temperatura atmosférica',\n       battery_level AS 'Nivel de batería',\n       dissolved_oxygen AS 'RAW DO',\n       do_15 AS 'DO at 15',\n       do_temp AS 'DO at current T°',\n       electrical_conductivity AS 'RAW EC',\n       ec_temp AS 'EC at current T°',\n       internal_humidity AS 'Humedad interna',\n       internal_pressure AS 'Presión interna',\n       internal_temperature AS 'Temperatura interna',\n       latitude AS 'Latitud',\n       longitude AS 'Longitud',\n       oxide_reduction_potential AS 'Potencial reducción',\n       ph AS 'RAW PH',\n       ph_temp AS 'PH at T°',\n       relative_density AS 'Densidad relativa',\n       salinity AS 'Salinidad',\n       total_dissolved_solids AS 'Total de sólidos disueltos',\n       water_temperature AS 'Temperatura del agua',\n       sat AS 'RAW SAT',\n       sat_temp AS 'SAT at current T°',\n       timestamp,\n       DATE_SUB(timestamp, INTERVAL 1 HOUR) AS timestamp_adj\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY id"
      }
     ]
    }
   ]
  }
 ]
}