{
 "title": "Humedat@ - ISF (Atlas beta)",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Introducción", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Léeme",
   "type": "text",
   "gridPos": { "h": 31, "w": 16, "x": 0, "y": 1 },
   "options": {
    "content": "# Humedat@ -- Isla San Francisco\n\nHas entrado al visualizador web de **Humedat@, plataforma en tiempo real para el monitoreo de calidad de aguas** de humedales de Chile.\n\n![Imágen de humedata](/public/img/Humedata_20221118_165704.jpg \"Humedat@ en acción!\")\n\nHumedat@ es una innovación tecnológica nacida en Valdivia, e impulsada por el [Centro de Humedales Río Cruces (CEHUM)](https://cehum.org/). \n\nConsiste en boyas de acero inox hechas con barriles cerveceros reutilizados, con múltiples sensores ambientales y electrónica de fuente abierta para la transmisión inalámbrica constante de datos desde diversos ecosistemas acuáticos hasta usuarios como tú. El aparato tiene tres conjuntos de sensores: 1) sensores acuáticos tales como T, pH, conductividad\neléctrica, oxígeno disuelto, y potencial de oxido-reducción; 2) sensores atmosféricos tales como temperatura y presión atmosférica; y 3) sensores internos que monitorean y resguardan el ambiente electrónico dentro del barril.\n\nEl desarrollo liderado por el [Dr. Cristián Correa](https://scholar.google.ca/citations?user=H3toP-0AAAAJ&hl=en) (cristiancorrea@gmail.com) ha contado con la colaboración del Laboratorio de Fabricación Digital [LeufüLab](https://leufulab.cl/) de la Facultad de Ciencias de la Ingeniería UACh. \nActualmente (2023) se encuentra financiado por el [Proyecto de Conservación Habitable Isla San Francisco](https://islasanfrancisco.cl/), con aportes de [Cerveza Kunstmann](https://cerveza-kunstmann.cl/).\n\nContáctanos para más información, cotizar, establecer sinergias estratégicas, colaborar o aportar monetaria o intelectualmente para que Humedat@ crezca al servicio de la educación y protección de humedales.\n\n![logo](/public/img/CEHUM_Logo_small.jpg \"Centro de Humedales Río Cruces\") ![logo](/public/img/Logo_Leufulab_small.jpg \"Leüfulab, Laboratorio de Fabricación Digital de la Facultad de Ciencias de la Ingeniería UACh\") ![logo](/public/img/Logo_UACH_small.jpg \"Universidad Austral de Chile\")\n\n# Observa el rítmo del humedal\nA continuación verás los datos que Humedat@ mide y tarnsmite en tiempo real desde el estuario del Río Valdivia junto a la Isla San Francisco. En conjunto, esta información revela el funcionamiento de este sistema ecológico, y permite advertir -- y reaccionar! -- tempranamente a cambios naturales o antropogénicos de su estado de salud ecosistémica.  \n\n![logo](/public/img/LOGO_ISFsmall.jpg \"Proyecto habitable Isla San Francisco\")  \n\n**Versión beta**: Vienen actualizaciones cosméticas y analíticas, incluyendo correcciones de parámetros de calidad de agua.   "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM logs\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Variables ambientales ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ubicación",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  latitude,\n  longitude\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = 1\nORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Presión Atmosférica",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  atmospheric_pressure * 10 AS `Presión Atmosférica`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) \n  AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18'OR timestamp > '2024-01-21 13:39:32')#  excluir período en lab.\nORDER BY timestamp"
    },
    {
     "rawSql": "# This query groups data by time period (e.g. 1 h) and calculates an average. \r\n# If no data is available in the period, it introduces a NULL value in order to display gaps in the graph.\r\n# The first chunk \"WITH AdjustedLogs AS (...)\" does the daylight saving time adjustment before the other calculations. \r\n# This was necessary to avoid problems created by combining macros with date adjustments. \r\n\r\nWITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        atmospheric_pressure*10 AS atmospheric_pressure\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(atmospheric_pressure) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');\r\n\r\n"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset (set it to 1 in winter) to account for daylight saving time. \n  atmospheric_temperature AS `Temperatura Atmosférica`,\n  #internal_temperature AS `Temperatura Interna`,\n  water_temperature AS `Temperatura del Agua`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) \n  AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp, # displaces the average curve\r\n        atmospheric_temperature,\r\n        water_temperature\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(atmospheric_temperature) AS 'promedio a la hora',\r\n    AVG(water_temperature) AS 'promedio a la hora '\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    }
   ]
  },
  {
   "title": "Oxígeno Disuelto",
   "type": "timeseries",
   "description": "0-3: Riesgo de anoxia\n3-5: Hipoxia\n5-10: Normoxia",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "mg/L" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  #dissolved_oxygen AS `DO`,\n  do_temp AS 'DO (T°)'#,\n  #do_15 AS 'DO at 15°C'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        do_temp \r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(do_temp) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');\r\n"
    }
   ]
  },
  {
   "title": "Saturación de Oxígeno (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  #sat AS `Sat DO`,\n  sat_temp AS 'Sat DO (T°)'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        sat\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(sat) AS 'promedio a la hora (oculto)'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    }
   ]
  },
  {
   "title": "Potencial de Óxido Reducción",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  oxide_reduction_potential AS `Potencial de Reduccción`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        oxide_reduction_potential\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(oxide_reduction_potential) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    }
   ]
  },
  {
   "title": "Conductividad Eléctrica",
   "type": "timeseries",
   "description": "El sensor actual mide en el rango 0.07 − 50,000 μS/cm. En enero 2024, el límite máximo fue superado en ISF y dejó de marcar. Requiere reemplazo.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "rawSql": "#Below, note condition \"electrical_conductivity > 0\", this is because there where mant zeroes, possibly due to probe range exceeded.  \nSELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  electrical_conductivity AS `RAW EC`,\n  ec_temp AS 'EC (T°)'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        ec_temp\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(ec_temp) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    }
   ]
  },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  (ph) AS 'pH'\n  #ph_temp 'pH at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        ph_temp\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(ph_temp) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    },
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  ph_temp 'pH compensado por T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Variables internas (estado de salud de boya)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Batería",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  battery_level\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = 1\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Voltaje Batería",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  battery_level\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        battery_level\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(battery_level) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    }
   ]
  },
  {
   "title": "Humedad Interna",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time. \n  internal_humidity AS `Humedad Interna`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        internal_humidity\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(internal_humidity) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    }
   ]
  },
  {
   "title": "Delta presión interna (hPa) ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  10 * (internal_pressure - atmospheric_pressure) AS `Delta Presión Interna (hPa)`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1 \n  AND timestamp >= '2023-09-15'\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\nORDER BY timestamp"
    },
    {
     "rawSql": "WITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        internal_pressure,\r\n        atmospheric_pressure\r\n    FROM logs\r\n   WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(10 * (internal_pressure - atmospheric_pressure)) AS 'promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');"
    }
   ]
  },
  {
   "title": "Temperatura interna del barril",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "# This query groups data by time period (e.g. 1 h) and calculates an average. \r\n# If no data is available in the period, it introduces a NULL value in order to display gaps in the graph.\r\n# The first chunk \"WITH AdjustedLogs AS (...)\" does the daylight saving time adjustment before the other calculations. \r\n# This was necessary to avoid problems created by combining macros with date adjustments. \r\n\r\nWITH AdjustedLogs AS (\r\n    SELECT \r\n        DATE_ADD(timestamp, INTERVAL 0.5 HOUR) AS adjusted_timestamp,\r\n        internal_temperature\r\n    FROM logs\r\n    WHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\n)\r\n\r\nSELECT\r\n    $__timeGroup(adjusted_timestamp, '1h') AS 'time',\r\n    AVG(internal_temperature) AS 'T° promedio a la hora'\r\nFROM AdjustedLogs\r\nGROUP BY \r\n    $__timeGroup(adjusted_timestamp, '1h',NULL)\r\nORDER BY \r\n    $__timeGroup(adjusted_timestamp, '1h');\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT\r\n  #timestamp AS \"time\",\r\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\r\n  internal_temperature AS `Datos recibidos`\r\nFROM logs\r\nWHERE\r\n  $__timeFilter(timestamp) AND dev_id = 1 \r\n  AND timestamp >= '2023-09-15'\r\n  AND (timestamp < '2023-12-28 09:00:18' OR timestamp > '2024-01-21 13:39:32') # period in lab\r\nORDER BY timestamp\r\n"
    }
   ]
  },
  {
   "title": "Tiempo entre mediciones recibidas remotamente",
   "type": "timeseries",
   "description": "Esto es para estudiar frecuencia de flujo de datos. Internamente Humedat@ registra mediaciones regularmente (actualmente programado cada 15 min).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "-- SQL Script for Grafana Dashboard to Monitor Time Elapsed Between Data Packages Reception\r\n\r\nSELECT\r\n  DATE_SUB(a.timestamp, INTERVAL 0 HOUR) AS \"time\",\r\n  TIMESTAMPDIFF(MINUTE, b.timestamp, a.timestamp) AS \"time_elapsed_in_minutes\"\r\nFROM\r\n  (SELECT *, @row_number_a:=@row_number_a + 1 AS rn FROM logs, (SELECT @row_number_a:=0) AS t \r\n  WHERE $__timeFilter(timestamp) AND dev_id = '1' ORDER BY timestamp) a\r\nJOIN\r\n  (SELECT *, @row_number_b:=@row_number_b + 1 AS rn FROM logs, (SELECT @row_number_b:=0) AS t \r\n  WHERE $__timeFilter(timestamp) AND dev_id = '1' ORDER BY timestamp) b\r\nON\r\n  a.rn = b.rn + 1\r\nORDER BY\r\n  a.timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Histograma de tiempo entre mediciones recibidas",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "-- SQL Script for Grafana Dashboard to Monitor Time Elapsed Between Data Packages Reception\r\n\r\nSELECT\r\n  DATE_SUB(a.timestamp, INTERVAL 1 HOUR) AS \"time\",\r\n  TIMESTAMPDIFF(MINUTE, b.timestamp, a.timestamp) AS \"time_elapsed_in_minutes\"\r\nFROM\r\n  (SELECT *, @row_number_a:=@row_number_a + 1 AS rn FROM logs, (SELECT @row_number_a:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '1' ORDER BY timestamp) a\r\nJOIN\r\n  (SELECT *, @row_number_b:=@row_number_b + 1 AS rn FROM logs, (SELECT @row_number_b:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '1' ORDER BY timestamp) b\r\nON\r\n  a.rn = b.rn + 1\r\nORDER BY\r\n  a.timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Live data",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  internal_humidity AS 'Humedad interna'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  10 * (internal_pressure - atmospheric_pressure) AS 'Presión int. (delta hPa)'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = 1\nORDER BY timestamp  "
    }
   ]
  },
  {
   "title": "Ayuda",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ayuda",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "options": {
      "content": "# Ayuda  \n## Modificar ventana de tiempo  \nIr a ícono Reloj (arriba, derecha). Seleccionar un rango absoluto de fechas, o bien, enfocarse en el último período de 6 h, 12 h, 24 h, 7 días, etc. \n## Refrescar\nHumedat@ despacha paquetes de datos regularmente (e.g., cada 15 min, según su configuración) aunque algunos de estos paquetes no llegan al servidor (mejoras pendientes). Como usuario final, tu puedes decidir cada cuánto tiempo se refresca tu visualización. Pincha el ícono Refresh para actualizar los gráficos con la última información disponible en el Servidor, y en el menú del costado elije la frecuencia de actualización auntomática. "
     },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM logs\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Tabla de datos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datos descargables en formato tabular",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM logs\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}