{
 "title": "Humedat@s",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "h_id",
    "label": "ID humedat@",
    "query": "SELECT id FROM Humedata_devices;"
   }
  ]
 },
 "panels": [
  {
   "title": "Tiempo entre medidas",
   "type": "timeseries",
   "description": "Para estudiar frecuencia de flujo de datos",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "-- SQL Script for Grafana Dashboard to Monitor Time Elapsed Between Data Packages Reception\r\n\r\nSELECT\r\n  DATE_SUB(a.timestamp, INTERVAL 1 HOUR) AS \"time\",\r\n  TIMESTAMPDIFF(MINUTE, b.timestamp, a.timestamp) AS \"time_elapsed_in_minutes\"\r\nFROM\r\n  (SELECT *, @row_number_a:=@row_number_a + 1 AS rn FROM logs, (SELECT @row_number_a:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '$h_id' ORDER BY timestamp) a\r\nJOIN\r\n  (SELECT *, @row_number_b:=@row_number_b + 1 AS rn FROM logs, (SELECT @row_number_b:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '$h_id' ORDER BY timestamp) b\r\nON\r\n  a.rn = b.rn + 1\r\nORDER BY\r\n  a.timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Tiempo entre medidas",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "-- SQL Script for Grafana Dashboard to Monitor Time Elapsed Between Data Packages Reception\r\n\r\nSELECT\r\n  DATE_SUB(a.timestamp, INTERVAL 1 HOUR) AS \"time\",\r\n  TIMESTAMPDIFF(MINUTE, b.timestamp, a.timestamp) AS \"time_elapsed_in_minutes\"\r\nFROM\r\n  (SELECT *, @row_number_a:=@row_number_a + 1 AS rn FROM logs, (SELECT @row_number_a:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '$h_id' ORDER BY timestamp) a\r\nJOIN\r\n  (SELECT *, @row_number_b:=@row_number_b + 1 AS rn FROM logs, (SELECT @row_number_b:=0) AS t WHERE $__timeFilter(timestamp) AND dev_id = '$h_id' ORDER BY timestamp) b\r\nON\r\n  a.rn = b.rn + 1\r\nORDER BY\r\n  a.timestamp;\r\n"
    }
   ]
  },
  {
   "title": "Dashboard - ALL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  atmospheric_temperature AS `Temperatura Atmosférica`,\n  internal_temperature AS `Temperatura Interna`,\n  water_temperature AS `Temperatura del Agua`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Presión",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    { "expression": "$A*10", "type": "math" }
   ]
  },
  {
   "title": "Ubicación",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  latitude,\n  longitude\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = '$h_id'\nORDER BY id DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Oxígeno Disuelto",
   "type": "timeseries",
   "description": "0-3: Riesgo de anoxia\n3-5: Hipoxia\n5-10: Normoxia",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mg/L" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  dissolved_oxygen AS `Raw DO`,\n  #do_15 AS 'DO at 15°C',\n  do_temp AS 'DO at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Porcentaje Saturación",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 0 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  sat AS `RAW SAT`,\n  sat_temp AS 'SAT at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "pH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pH" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  ph AS 'pH',\n  ph_temp 'pH at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Potencial de Óxido Reducción",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  oxide_reduction_potential AS `Potencial de Reduccción`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Humedad Interna",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  internal_humidity AS `Humedad Interna`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Conductividad Eléctrica",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "μS/cm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  electrical_conductivity AS `RAW EC`,\n  ec_temp AS 'Spec. EC (T° comp.)'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Voltaje Batería",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  battery_level\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Delta presión interna (hPa) ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  #timestamp AS \"time\",\n  DATE_SUB(timestamp, INTERVAL 1 HOUR) AS \"time\",# This is a offset to account for daylight saving time.\n  \n  10 * (internal_pressure - atmospheric_pressure) AS `Delta Presión Interna (hPa)`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp\n"
    }
   ]
  },
  {
   "title": "Vitales",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatura",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  atmospheric_temperature AS `Temperatura Atmosférica`,\n  water_temperature AS `Temperatura del Agua`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Presión",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      { "expression": "$A*10", "type": "math" }
     ]
    },
    {
     "title": "Ubicación",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  latitude,\n  longitude\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = '$h_id'\nORDER BY id DESC LIMIT 1"
      }
     ]
    },
    {
     "title": "Oxígeno Disuelto",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "mg/L" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  dissolved_oxygen AS `Raw DO`,\n  do_15 AS 'DO at 15°C',\n  do_temp AS 'DO at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Porcentaje Saturación",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sat AS `RAW SAT`,\n  sat_temp AS 'SAT at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "pH",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pH" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  ph AS 'pH',\n  ph_temp 'pH at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Potencial de Óxido Reducción",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "mvolt" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  oxide_reduction_potential AS `Potencial de Reduccción`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Sólidos Disueltos Totales",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  total_dissolved_solids\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Conductividad Eléctrica",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "μS/cm" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  electrical_conductivity AS `RAW EC`,\n  ec_temp AS 'EC at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Funcionamiento interno",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live data",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_humidity AS 'Humedad interna'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      },
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_pressure AS 'Presión interna'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp  "
      },
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_temperature AS 'Temperatura interna'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp  "
      }
     ]
    },
    {
     "title": "Temperatura interna",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 12, "y": 74 },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_temperature AS `Temperatura Interna`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Batería",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 4, "x": 20, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  battery_level\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Presión interna",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      { "expression": "$B*10", "type": "math" }
     ]
    },
    {
     "title": "Humedad Interna",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  internal_humidity AS `Humedad Interna`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Live data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperaturas",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  atmospheric_temperature AS `Atmosférica`,\n  internal_temperature AS `Interna`,\n  water_temperature AS `Agua`\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Oxígeno Disuelto",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "mg/L" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  dissolved_oxygen AS `Raw`,\n  do_15 AS 'DO at 15°C',\n  do_temp AS 'DO at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Ubicación",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  latitude,\n  longitude\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = '$h_id'\nORDER BY id DESC LIMIT 1"
      }
     ]
    },
    {
     "title": "pH",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "pH" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  ph AS 'Raw',\n  ph_temp 'pH at Current T°'\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND\n  dev_id = '$h_id'\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Registros",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Datos históricos Humedat@ Atlas",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT id,\n       #atmospheric_pressure AS 'Presión atmosférica',\n       #atmospheric_temperature AS 'Temperatura atmosférica',\n       battery_level AS 'Nivel de batería',\n       dissolved_oxygen AS 'RAW DO',\n       #do_15 AS 'DO at 15',\n       #do_temp AS 'DO at current T°',\n       sat AS 'RAW SAT',\n      # sat_temp AS 'SAT at current T°',\n       electrical_conductivity AS 'RAW EC',\n       #ec_temp AS 'EC at current T°',\n       #internal_humidity AS 'Humedad interna',\n       #internal_pressure AS 'Presión interna',\n       #internal_temperature AS 'Temperatura interna',\n       latitude AS 'Latitud',\n       longitude AS 'Longitud',\n       #oxide_reduction_potential AS 'Potencial reducción',\n       ph AS 'RAW PH',\n       #ph_temp AS 'PH at T°',\n      # relative_density AS 'Densidad relativa',\n       #salinity AS 'Salinidad',\n       #total_dissolved_solids AS 'Total de sólidos disueltos',\n       #water_temperature AS 'Temperatura del agua',\n       timestamp\nFROM logs\nWHERE\n  $__timeFilter(timestamp) AND dev_id = '$h_id'\nORDER BY id"
    }
   ]
  }
 ]
}