name: Commit Review

on:
  push:  # Triggered on pushes to any branch
    branches:
    - '**'

jobs:
  review:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install code-diff-review
      - name: Run Python script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.COMMIT_ASSISTANT }}
          GH_TOKEN: ${{ secrets.GH_API_KEY }}
          REPO: ${{ github.repository }}
          MESSAGE: ${{github.event.head_commit.message}}
          GH_BEFORE: ${{ github.event.before }} 
          SHA: ${{ github.sha }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
          WEBSECRET: ${{ secrets.WEBSECRET }}
        run: |
          code-diff-review \
            --openai-key "$OPENAI_API_KEY" \
            --assistant-id "$OPENAI_ASSISTANT_ID" \
            --token "$GH_TOKEN" \
            --repo "$REPO" \
            --message "$MESSAGE" \
            --gh-before "$GH_BEFORE" \
            --sha "$SHA" \
            --author "$AUTHOR" \
            --webhook "$WEBHOOK" \
            --websecret "$WEBSECRET"